"""Initial migration.

Revision ID: c56d86198179
Revises:
Create Date: 2021-03-15 00:49:55.604731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c56d86198179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address_1', sa.String(length=150), nullable=False),
                    sa.Column('address_2', sa.String(length=150), nullable=True),
                    sa.Column('city', sa.String(length=150), nullable=False),
                    sa.Column('country', sa.String(length=30), nullable=False),
                    sa.Column('state', sa.String(length=50), nullable=False),
                    sa.Column('zipcode', sa.String(length=10), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('email_new', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(length=50), nullable=False),
                    sa.Column('last_name', sa.String(length=50), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('password_new', sa.String(), nullable=True),
                    sa.Column('prefix', postgresql.ENUM('Miss', 'Mr', 'Mrs', 'Ms', 'Mx', name='user_prefix_enum'), nullable=True),
                    sa.Column('status', postgresql.ENUM('Active', 'Banned', 'Inactive', 'Pending', name='user_status_enum'), nullable=False),
                    sa.Column('telephone', sa.String(length=50), nullable=True),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_new'), 'users', ['email_new'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email_new'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('addresses')
    # ### end Alembic commands ###
